package com.example.organize

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import io.realm.Realm
import io.realm.kotlin.where
import org.apache.commons.csv.CSVFormat
import java.io.*

class MainActivity : AppCompatActivity() {
    private lateinit var realm: Realm
    private var result = ""

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        realm = Realm.getDefaultInstance()

        readData()

        val file = "result.csv"
        File(applicationContext.filesDir, file).writer().use {
            it.write(result)
        }

    }

    private fun readData() {
        val reader = BufferedReader(InputStreamReader(resources.assets.open("sample.csv")))
        reader.use {
            val records = CSVFormat.EXCEL.parse(reader)
            realm.executeTransaction {
                val target = realm.where<Data>().findAll()
                target.deleteAllFromRealm()
                records.records.forEach { record ->
                    convert(record[12])
                }
            }
        }
    }

    private fun convert(x: String) {
        when (x) {
            "雨" -> result += ",1"
            "大雨" -> result += ",1"
            "雨、大風を伴う" -> result += ",1"
            "時々雨、霧を伴う" -> result += ",1"
            "一時雨、大風を伴う" -> result += ",1"
            "大雨、大風を伴う" -> result += ",1"
            "雨、霧を伴う" -> result += ",1"
            "雨時々曇" -> result += ",1"
            "雨後曇、霧を伴う" -> result += ",1"
            "雨時々曇一時霧" -> result += ",1"
            "雨一時霧" -> result += ",1"
            "雨一時曇" -> result += ",1"
            "雨後晴" -> result += ",1"
            "曇後雨" -> result += ",1"
            "雨一時霧後曇" -> result += ",1"
            "雨後曇" -> result += ",1"
            "曇後雨、雷を伴う" -> result += ",1"
            "雨後晴、雷を伴う" -> result += ",1"
            "雨後曇一時晴" -> result += ",1"
            "雨、雷を伴う" -> result += ",1"
            "曇時々晴後雨" -> result += ",1"
            "雨一時みぞれ" -> result += ",1"
            "雪後雨" -> result += ",1"
            "雨一時曇、雷を伴う" -> result += ",1"
            "大雨後晴、雷を伴う" -> result += ",1"
            "大雨時々曇、雷を伴う" -> result += ",1"
            "大雨後晴" -> result += ",1"
            "雪後雨一時曇" -> result += ",1"
            "雨時々曇一時晴" -> result += ",1"
            "雨一時曇、霧を伴う" -> result += ",1"
            "曇後雨、霧を伴う" -> result += ",1"
            "雨後晴、霧を伴う" -> result += ",1"
            "雨時々曇、霧を伴う" -> result += ",1"
            "雨後晴一時曇" -> result += ",1"
            "大雨後曇、霧を伴う" -> result += ",1"
            "大雨、霧を伴う" -> result += ",1"
            "雨一時曇、みぞれを伴う" -> result += ",1"
            "雨時々曇、雷を伴う" -> result += ",1"
            "雨後一時曇" -> result += ",1"
            "曇後大雨" -> result += ",1"
            "大雨一時曇" -> result += ",1"
            "晴後大雨、雷を伴う" -> result += ",1"
            "大雨後曇" -> result += ",1"
            "大雨後一時晴" -> result += ",1"
            "大雨、雷を伴う" -> result += ",1"
            "雨後時々曇" -> result += ",1"
            "雨後時々晴" -> result += ",1"
            "晴後雨" -> result += ",1"
            "雨時々曇後晴" -> result += ",1"
            "雨後時々曇、霧を伴う" -> result += ",1"
            "雨一時霧雨後曇" -> result += ",1"
            "大雨後一時曇" -> result += ",1"
            "雨後一時曇、霧を伴う" -> result += ",1"
            "雨一時みぞれ、雷を伴う" -> result += ",1"
            "雨一時晴" -> result += ",1"
            "雨一時曇後晴" -> result += ",1"
            "雨後曇、雷を伴う" -> result += ",1"
            "雨一時霧雨" -> result += ",1"
            "雨後薄曇、雷を伴う" -> result += ",1"
            "雨後一時晴" -> result += ",1"
            "雨一時曇、大風を伴う" -> result += ",1"
            "大雨一時曇、雷を伴う" -> result += ",1"
            "雨後曇、みぞれを伴う" -> result += ",1"
            "雨後曇時々晴" -> result += ",1"
            "曇後雨一時晴" -> result += ",1"
            "暴風雨" -> result += ",1"
            "雨後曇一時晴、みぞれを伴う" -> result += ",1"
            "大雨後時々曇" -> result += ",1"
            "大雨後曇一時晴" -> result += ",1"
            "雨後曇一時晴、雷を伴う" -> result += ",1"
            "雨時々曇一時みぞれ" -> result += ",1"
            "晴後雨、雷を伴う" -> result += ",1"
            "曇後大雨、雷を伴う" -> result += ",1"
            "大雨後曇、雷を伴う" -> result += ",1"
            "雨時々曇後一時晴、みぞれを伴う" -> result += ",1"
            "雨後薄曇時々晴" -> result += ",1"
            "雨一時曇、大風・雷を伴う" -> result += ",1"
            "曇時々晴後大雨、雷を伴う" -> result += ",1"
            "薄曇後雨" -> result += ",1"
            "大雨後曇時々晴" -> result += ",1"
            "雨後晴一時曇、雷を伴う" -> result += ",1"
            "雨後薄曇" -> result += ",1"
            "みぞれ後雨" -> result += ",1"
            "大雨一時曇、霧を伴う" -> result += ",1"
            "大雨時々曇" -> result += ",1"
            "雨時々曇、大風を伴う" -> result += ",1"
            "雨後曇後一時晴" -> result += ",1"
            "雨後晴時々薄曇" -> result += ",1"
            "大雨後一時曇、雷を伴う" -> result += ",1"
            "雨時々曇一時晴、雷を伴う" -> result += ",1"
            "雨一時雪" -> result += ",1"
            "晴" -> result += ",2"
            "晴時々雪" -> result += ",2"
            "晴時々雨" -> result += ",2"
            "晴一時雨" -> result += ",2"
            "晴一時雪" -> result += ",2"
            "大風　降水なし" -> result += ",2"
            "快晴" -> result += ",2"
            "晴一時曇" -> result += ",2"
            "晴後曇一時雨" -> result += ",2"
            "晴後曇" -> result += ",2"
            "晴時々曇一時雨" -> result += ",2"
            "晴時々曇" -> result += ",2"
            "晴後曇一時雪" -> result += ",2"
            "晴後一時雨" -> result += ",2"
            "晴後薄曇" -> result += ",2"
            "晴後曇時々雨" -> result += ",2"
            "晴一時雨、雷を伴う" -> result += ",2"
            "晴後一時曇" -> result += ",2"
            "晴時々曇一時雪" -> result += ",2"
            "晴後時々曇" -> result += ",2"
            "晴一時薄曇" -> result += ",2"
            "晴一時雨、あられを伴う" -> result += ",2"
            "晴後曇一時雨、雷を伴う" -> result += ",2"
            "晴時々薄曇" -> result += ",2"
            "晴一時霧" -> result += ",2"
            "晴、雷を伴う" -> result += ",2"
            "晴時々曇、雷を伴う" -> result += ",2"
            "晴後一時雨、雷を伴う" -> result += ",2"
            "晴後時々雨" -> result += ",2"
            "晴一時みぞれ" -> result += ",2"
            "晴後曇時々雪" -> result += ",2"
            "晴後一時薄曇" -> result += ",2"
            "晴後雨、みぞれを伴う" -> result += ",2"
            "晴後一時曇、雷を伴う" -> result += ",2"
            "晴後時々曇一時みぞれ" -> result += ",2"
            "晴後時々薄曇" -> result += ",2"
            "晴後一時雪" -> result += ",2"
            "晴後曇、雷を伴う" -> result += ",2"
            "晴後時々雨一時みぞれ" -> result += ",2"
            "晴後曇一時雨、あられを伴う" -> result += ",2"
            "晴時々曇一時雨、雷を伴う" -> result += ",2"
            "晴一時雨、みぞれを伴う" -> result += ",2"
            "晴後時々曇一時雨" -> result += ",2"
            "晴後曇一時みぞれ" -> result += ",2"
            "晴時々曇一時雨、あられを伴う" -> result += ",2"
            "晴一時雪、あられを伴う" -> result += ",2"
            "晴時々雨一時曇" -> result += ",2"
            "晴時々曇一時雪、みぞれを伴う" -> result += ",2"
            "晴後雪時々曇、みぞれを伴う" -> result += ",2"
            "晴時々雨、雷を伴う" -> result += ",2"
            "晴時々曇後一時雨、雷を伴う" -> result += ",2"
            "晴時々曇後一時雨" -> result += ",2"
            "晴一時曇、霧を伴う" -> result += ",2"
            "晴後時々曇一時雨、雷を伴う" -> result += ",2"
            "晴一時雨後薄曇" -> result += ",2"
            "晴後曇時々雪、あられを伴う" -> result += ",2"
            "晴、霧を伴う" -> result += ",2"
            "晴後時々雨、雷を伴う" -> result += ",2"
            "晴時々雨、あられを伴う" -> result += ",2"
            "晴時々曇一時みぞれ" -> result += ",2"
            "曇" -> result += ",3"
            "曇一時雪" -> result += ",3"
            "曇時々雨" -> result += ",3"
            "曇一時雨" -> result += ",3"
            "曇時々雪" -> result += ",3"
            "曇一時雨後晴" -> result += ",3"
            "曇一時晴後雨" -> result += ",3"
            "曇時々晴" -> result += ",3"
            "曇時々晴一時雨" -> result += ",3"
            "曇一時晴" -> result += ",3"
            "薄曇" -> result += ",3"
            "曇一時雨、霧を伴う" -> result += ",3"
            "曇時々晴一時雨、雷を伴う" -> result += ",3"
            "曇時々雨一時霧" -> result += ",3"
            "曇後晴" -> result += ",3"
            "曇時々雨後晴" -> result += ",3"
            "曇時々雨一時晴" -> result += ",3"
            "曇時々雨、雷を伴う" -> result += ",3"
            "曇後時々雨" -> result += ",3"
            "曇後一時雨" -> result += ",3"
            "曇時々みぞれ" -> result += ",3"
            "曇時々晴一時雪" -> result += ",3"
            "曇後一時大雨、雷を伴う" -> result += ",3"
            "曇一時雨、雷を伴う" -> result += ",3"
            "曇後時々雨、雷を伴う" -> result += ",3"
            "曇一時みぞれ後晴" -> result += ",3"
            "曇時々みぞれ後晴" -> result += ",3"
            "曇時々雪一時晴" -> result += ",3"
            "薄曇後晴" -> result += ",3"
            "曇一時霧後晴" -> result += ",3"
            "曇一時雨、あられを伴う" -> result += ",3"
            "曇一時雨、雷・ひょうを伴う" -> result += ",3"
            "曇後一時晴" -> result += ",3"
            "薄曇一時晴" -> result += ",3"
            "曇時々雨、霧を伴う" -> result += ",3"
            "曇後一時雨、雷を伴う" -> result += ",3"
            "薄曇時々晴" -> result += ",3"
            "曇一時雨後時々晴" -> result += ",3"
            "曇一時晴、雷を伴う" -> result += ",3"
            "曇後時々雪" -> result += ",3"
            "曇後時々晴" -> result += ",3"
            "曇一時雪後晴" -> result += ",3"
            "曇時々みぞれ一時晴" -> result += ",3"
            "曇後晴一時雪" -> result += ",3"
            "曇、霧を伴う" -> result += ",3"
            "曇時々雨一時晴、雷を伴う" -> result += ",3"
            "薄曇後一時晴" -> result += ",3"
            "曇時々雨一時雪" -> result += ",3"
            "薄曇一時雪" -> result += ",3"
            "曇時々雨、雷・あられを伴う" -> result += ",3"
            "曇時々大雨後晴、雷を伴う" -> result += ",3"
            "曇、雷を伴う" -> result += ",3"
            "曇時々晴、雷を伴う" -> result += ",3"
            "曇一時みぞれ" -> result += ",3"
            "曇後雨一時雪" -> result += ",3"
            "曇後一時みぞれ" -> result += ",3"
            "薄曇、雷を伴う" -> result += ",3"
            "薄曇後一時大雨、雷を伴う" -> result += ",3"
            "曇時々大雨、雷を伴う" -> result += ",3"
            "曇時々晴一時みぞれ" -> result += ",3"
            "曇時々晴、あられを伴う " -> result += ",3"
            "曇一時雨後晴、霧を伴う" -> result += ",3"
            "薄曇一時雨" -> result += ",3"
            "曇時々晴後一時雨" -> result += ",3"
            "曇後晴、雷を伴う" -> result += ",3"
            "薄曇後時々晴" -> result += ",3"
            "曇一時晴後雨、霧を伴う" -> result += ",3"
            "曇時々雨一時晴、みぞれを伴う" -> result += ",3"
            "曇後一時雪" -> result += ",3"
            "曇後一時晴、霧を伴う" -> result += ",3"
            "曇後時々雨一時晴、雷を伴う" -> result += ",3"
            "曇時々雪後晴" -> result += ",3"
            "曇時々晴一時雨、みぞれを伴う" -> result += ",3"
            "曇時々晴一時雨、あられを伴う" -> result += ",3"
            "曇時々晴後一時雨、雷を伴う" -> result += ",3"
            "曇後晴、霧を伴う" -> result += ",3"
            "曇一時雪後晴、みぞれを伴う" -> result += ",3"
            "曇時々晴後一時みぞれ" -> result += ",3"
            "曇時々雨後一時晴" -> result += ",3"
            "曇時々晴一時雪、みぞれを伴う" -> result += ",3"
            "曇一時雪後時々晴" -> result += ",3"
            "曇時々みぞれ後晴、あられを伴う" -> result += ",3"
            "曇一時晴後時々雨" -> result += ",3"
            "曇後時々晴、雷を伴う" -> result += ",3"
            "曇一時大雨、雷を伴う" -> result += ",3"
            "曇一時雨後晴、雷を伴う" -> result += ",3"
            "曇後一時あられ" -> result += ",3"
            "薄曇後一時雨" -> result += ",3"
            "曇一時晴後時々雨、雷を伴う" -> result += ",3"
            "曇時々大雨" -> result += ",3"
            "曇一時雨後一時晴" -> result += ",3"
            "曇時々雨後晴、雷を伴う" -> result += ",3"
            "曇時々晴、みぞれを伴う" -> result += ",3"
            "曇後時々雨一時晴" -> result += ",3"
            "曇一時大雨" -> result += ",3"
            "雪" -> result += ",4"
            "大雪" -> result += ",4"
            "雪後晴" -> result += ",4"
            "みぞれ後晴" -> result += ",4"
            "雪時々雨後曇" -> result += ",4"
            "雪一時晴" -> result += ",4"
            "雪一時曇" -> result += ",4"
            "雪時々晴" -> result += ",4"
            "雪後一時晴" -> result += ",4"
            "雪時々曇" -> result += ",4"
            "雪後時々曇" -> result += ",4"
            "雪後みぞれ" -> result += ",4"
            "曇後大雪" -> result += ",4"
            "雪後時々雨" -> result += ",4"
            "雪後一時曇、みぞれを伴う" -> result += ",4"
            "みぞれ時々曇後雪" -> result += ",4"
            "雪後曇時々晴" -> result += ",4"
            "大雪後晴" -> result += ",4"
            "みぞれ一時雪後晴" -> result += ",4"
            "雪後一時雨" -> result += ",4"
            "雪後薄曇一時晴" -> result += ",4"
            "雪時々曇後晴" -> result += ",4"
            "雪後みぞれ一時曇" -> result += ",4"
            "雪後晴時々曇、みぞれを伴う" -> result += ",4"
            "雪時々曇一時晴" -> result += ",4"
            else -> result += ",0"
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        realm.close()
    }
}