package com.example.organize

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import io.realm.Realm
import io.realm.kotlin.where
import org.apache.commons.csv.CSVFormat
import java.io.*

class MainActivity : AppCompatActivity() {
    private lateinit var realm: Realm
    private var result = ""

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        realm = Realm.getDefaultInstance()

        readData()

        val file = "result.csv"
        File(applicationContext.filesDir, file).writer().use {
            it.write(result)
        }

    }

    private fun readData() {
        val reader = BufferedReader(InputStreamReader(resources.assets.open("sample.csv")))
        reader.use {
            val records = CSVFormat.EXCEL.parse(reader)
            records.records.forEach { record ->
                result += convert(record[12])
            }
        }
    }

    private fun convert(x: String) {
        when (x) {
            "雨" -> result += ",1"
            "大雨" -> result += ",2"
            "雨、大風を伴う" -> result += ",3"
            "時々雨、霧を伴う" -> result += ",4"
            "一時雨、大風を伴う" -> result += ",5"
            "大雨、大風を伴う" -> result += ",6"
            "雨、霧を伴う" -> result += ",7"
            "雨時々曇" -> result += ",8"
            "雨後曇、霧を伴う" -> result += ",9"
            "雨時々曇一時霧" -> result += ",10"
            "雨一時霧" -> result += ",11"
            "雨一時曇" -> result += ",12"
            "雨後晴" -> result += ",13"
            "曇後雨" -> result += ",14"
            "雨一時霧後曇" -> result += ",15"
            "雨後曇" -> result += ",16"
            "曇後雨、雷を伴う" -> result += ",17"
            "雨後晴、雷を伴う" -> result += ",18"
            "雨後曇一時晴" -> result += ",19"
            "雨、雷を伴う" -> result += ",20"
            "曇時々晴後雨" -> result += ",21"
            "雨一時みぞれ" -> result += ",22"
            "雪後雨" -> result += ",23"
            "雨一時曇、雷を伴う" -> result += ",24"
            "大雨後晴、雷を伴う" -> result += ",25"
            "大雨時々曇、雷を伴う" -> result += ",26"
            "大雨後晴" -> result += ",27"
            "雪後雨一時曇" -> result += ",28"
            "雨時々曇一時晴" -> result += ",29"
            "雨一時曇、霧を伴う" -> result += ",30"
            "曇後雨、霧を伴う" -> result += ",31"
            "雨後晴、霧を伴う" -> result += ",32"
            "雨時々曇、霧を伴う" -> result += ",33"
            "雨後晴一時曇" -> result += ",34"
            "大雨後曇、霧を伴う" -> result += ",35"
            "大雨、霧を伴う" -> result += ",36"
            "雨一時曇、みぞれを伴う" -> result += ",37"
            "雨時々曇、雷を伴う" -> result += ",38"
            "雨後一時曇" -> result += ",39"
            "曇後大雨" -> result += ",40"
            "大雨一時曇" -> result += ",41"
            "晴後大雨、雷を伴う" -> result += ",42"
            "大雨後曇" -> result += ",43"
            "大雨後一時晴" -> result += ",44"
            "大雨、雷を伴う" -> result += ",45"
            "雨後時々曇" -> result += ",46"
            "雨後時々晴" -> result += ",47"
            "晴後雨" -> result += ",48"
            "雨時々曇後晴" -> result += ",49"
            "雨後時々曇、霧を伴う" -> result += ",50"
            "雨一時霧雨後曇" -> result += ",51"
            "大雨後一時曇" -> result += ",52"
            "雨後一時曇、霧を伴う" -> result += ",53"
            "雨一時みぞれ、雷を伴う" -> result += ",54"
            "雨一時晴" -> result += ",55"
            "雨一時曇後晴" -> result += ",56"
            "雨後曇、雷を伴う" -> result += ",57"
            "雨一時霧雨" -> result += ",58"
            "雨後薄曇、雷を伴う" -> result += ",59"
            "雨後一時晴" -> result += ",60"
            "雨一時曇、大風を伴う" -> result += ",61"
            "大雨一時曇、雷を伴う" -> result += ",62"
            "雨後曇、みぞれを伴う" -> result += ",63"
            "雨後曇時々晴" -> result += ",64"
            "曇後雨一時晴" -> result += ",65"
            "暴風雨" -> result += ",66"
            "雨後曇一時晴、みぞれを伴う" -> result += ",67"
            "大雨後時々曇" -> result += ",68"
            "大雨後曇一時晴" -> result += ",69"
            "雨後曇一時晴、雷を伴う" -> result += ",70"
            "雨時々曇一時みぞれ" -> result += ",71"
            "晴後雨、雷を伴う" -> result += ",72"
            "曇後大雨、雷を伴う" -> result += ",73"
            "大雨後曇、雷を伴う" -> result += ",74"
            "雨時々曇後一時晴、みぞれを伴う" -> result += ",75"
            "雨後薄曇時々晴" -> result += ",76"
            "雨一時曇、大風・雷を伴う" -> result += ",77"
            "曇時々晴後大雨、雷を伴う" -> result += ",78"
            "薄曇後雨" -> result += ",79"
            "大雨後曇時々晴" -> result += ",80"
            "雨後晴一時曇、雷を伴う" -> result += ",81"
            "雨後薄曇" -> result += ",82"
            "みぞれ後雨" -> result += ",83"
            "大雨一時曇、霧を伴う" -> result += ",84"
            "大雨時々曇" -> result += ",85"
            "雨時々曇、大風を伴う" -> result += ",86"
            "雨後曇後一時晴" -> result += ",87"
            "雨後晴時々薄曇" -> result += ",88"
            "大雨後一時曇、雷を伴う" -> result += ",89"
            "雨時々曇一時晴、雷を伴う" -> result += ",90"
            "雨一時雪" -> result += ",91"
            "晴" -> result += ",92"
            "晴時々雪" -> result += ",93"
            "晴時々雨" -> result += ",94"
            "晴一時雨" -> result += ",95"
            "晴一時雪" -> result += ",96"
            "大風　降水なし" -> result += ",97"
            "快晴" -> result += ",98"
            "晴一時曇" -> result += ",99"
            "晴後曇一時雨" -> result += ",100"
            "晴後曇" -> result += ",101"
            "晴時々曇一時雨" -> result += ",102"
            "晴時々曇" -> result += ",103"
            "晴後曇一時雪" -> result += ",104"
            "晴後一時雨" -> result += ",105"
            "晴後薄曇" -> result += ",106"
            "晴後曇時々雨" -> result += ",107"
            "晴一時雨、雷を伴う" -> result += ",108"
            "晴後一時曇" -> result += ",109"
            "晴時々曇一時雪" -> result += ",110"
            "晴後時々曇" -> result += ",111"
            "晴一時薄曇" -> result += ",112"
            "晴一時雨、あられを伴う" -> result += ",113"
            "晴後曇一時雨、雷を伴う" -> result += ",114"
            "晴時々薄曇" -> result += ",115"
            "晴一時霧" -> result += ",116"
            "晴、雷を伴う" -> result += ",117"
            "晴時々曇、雷を伴う" -> result += ",118"
            "晴後一時雨、雷を伴う" -> result += ",119"
            "晴後時々雨" -> result += ",120"
            "晴一時みぞれ" -> result += ",121"
            "晴後曇時々雪" -> result += ",122"
            "晴後一時薄曇" -> result += ",123"
            "晴後雨、みぞれを伴う" -> result += ",124"
            "晴後一時曇、雷を伴う" -> result += ",125"
            "晴後時々曇一時みぞれ" -> result += ",126"
            "晴後時々薄曇" -> result += ",127"
            "晴後一時雪" -> result += ",128"
            "晴後曇、雷を伴う" -> result += ",129"
            "晴後時々雨一時みぞれ" -> result += ",130"
            "晴後曇一時雨、あられを伴う" -> result += ",131"
            "晴時々曇一時雨、雷を伴う" -> result += ",132"
            "晴一時雨、みぞれを伴う" -> result += ",133"
            "晴後時々曇一時雨" -> result += ",134"
            "晴後曇一時みぞれ" -> result += ",135"
            "晴時々曇一時雨、あられを伴う" -> result += ",136"
            "晴一時雪、あられを伴う" -> result += ",137"
            "晴時々雨一時曇" -> result += ",138"
            "晴時々曇一時雪、みぞれを伴う" -> result += ",139"
            "晴後雪時々曇、みぞれを伴う" -> result += ",140"
            "晴時々雨、雷を伴う" -> result += ",141"
            "晴時々曇後一時雨、雷を伴う" -> result += ",142"
            "晴時々曇後一時雨" -> result += ",143"
            "晴一時曇、霧を伴う" -> result += ",144"
            "晴後時々曇一時雨、雷を伴う" -> result += ",145"
            "晴一時雨後薄曇" -> result += ",146"
            "晴後曇時々雪、あられを伴う" -> result += ",147"
            "晴、霧を伴う" -> result += ",148"
            "晴後時々雨、雷を伴う" -> result += ",149"
            "晴時々雨、あられを伴う" -> result += ",150"
            "晴時々曇一時みぞれ" -> result += ",151"
            "曇" -> result += ",152"
            "曇一時雪" -> result += ",153"
            "曇時々雨" -> result += ",154"
            "曇一時雨" -> result += ",155"
            "曇時々雪" -> result += ",156"
            "曇一時雨後晴" -> result += ",157"
            "曇一時晴後雨" -> result += ",158"
            "曇時々晴" -> result += ",159"
            "曇時々晴一時雨" -> result += ",160"
            "曇一時晴" -> result += ",161"
            "薄曇" -> result += ",162"
            "曇一時雨、霧を伴う" -> result += ",163"
            "曇時々晴一時雨、雷を伴う" -> result += ",164"
            "曇時々雨一時霧" -> result += ",165"
            "曇後晴" -> result += ",166"
            "曇時々雨後晴" -> result += ",167"
            "曇時々雨一時晴" -> result += ",168"
            "曇時々雨、雷を伴う" -> result += ",169"
            "曇後時々雨" -> result += ",170"
            "曇後一時雨" -> result += ",171"
            "曇時々みぞれ" -> result += ",172"
            "曇時々晴一時雪" -> result += ",173"
            "曇後一時大雨、雷を伴う" -> result += ",174"
            "曇一時雨、雷を伴う" -> result += ",175"
            "曇後時々雨、雷を伴う" -> result += ",176"
            "曇一時みぞれ後晴" -> result += ",177"
            "曇時々みぞれ後晴" -> result += ",178"
            "曇時々雪一時晴" -> result += ",179"
            "薄曇後晴" -> result += ",180"
            "曇一時霧後晴" -> result += ",181"
            "曇一時雨、あられを伴う" -> result += ",182"
            "曇一時雨、雷・ひょうを伴う" -> result += ",183"
            "曇後一時晴" -> result += ",184"
            "薄曇一時晴" -> result += ",185"
            "曇時々雨、霧を伴う" -> result += ",186"
            "曇後一時雨、雷を伴う" -> result += ",187"
            "薄曇時々晴" -> result += ",188"
            "曇一時雨後時々晴" -> result += ",189"
            "曇一時晴、雷を伴う" -> result += ",190"
            "曇後時々雪" -> result += ",191"
            "曇後時々晴" -> result += ",192"
            "曇一時雪後晴" -> result += ",193"
            "曇時々みぞれ一時晴" -> result += ",194"
            "曇後晴一時雪" -> result += ",195"
            "曇、霧を伴う" -> result += ",196"
            "曇時々雨一時晴、雷を伴う" -> result += ",197"
            "薄曇後一時晴" -> result += ",198"
            "曇時々雨一時雪" -> result += ",199"
            "薄曇一時雪" -> result += ",200"
            "曇時々雨、雷・あられを伴う" -> result += ",201"
            "曇時々大雨後晴、雷を伴う" -> result += ",202"
            "曇、雷を伴う" -> result += ",203"
            "曇時々晴、雷を伴う" -> result += ",204"
            "曇一時みぞれ" -> result += ",205"
            "曇後雨一時雪" -> result += ",206"
            "曇後一時みぞれ" -> result += ",207"
            "薄曇、雷を伴う" -> result += ",208"
            "薄曇後一時大雨、雷を伴う" -> result += ",209"
            "曇時々大雨、雷を伴う" -> result += ",210"
            "曇時々晴一時みぞれ" -> result += ",211"
            "曇時々晴、あられを伴う " -> result += ",212"
            "曇一時雨後晴、霧を伴う" -> result += ",213"
            "薄曇一時雨" -> result += ",214"
            "曇時々晴後一時雨" -> result += ",215"
            "曇後晴、雷を伴う" -> result += ",216"
            "薄曇後時々晴" -> result += ",217"
            "曇一時晴後雨、霧を伴う" -> result += ",218"
            "曇時々雨一時晴、みぞれを伴う" -> result += ",219"
            "曇後一時雪" -> result += ",220"
            "曇後一時晴、霧を伴う" -> result += ",221"
            "曇後時々雨一時晴、雷を伴う" -> result += ",222"
            "曇時々雪後晴" -> result += ",223"
            "曇時々晴一時雨、みぞれを伴う" -> result += ",224"
            "曇時々晴一時雨、あられを伴う" -> result += ",225"
            "曇時々晴後一時雨、雷を伴う" -> result += ",226"
            "曇後晴、霧を伴う" -> result += ",227"
            "曇一時雪後晴、みぞれを伴う" -> result += ",228"
            "曇時々晴後一時みぞれ" -> result += ",229"
            "曇時々雨後一時晴" -> result += ",230"
            "曇時々晴一時雪、みぞれを伴う" -> result += ",231"
            "曇一時雪後時々晴" -> result += ",232"
            "曇時々みぞれ後晴、あられを伴う" -> result += ",233"
            "曇一時晴後時々雨" -> result += ",234"
            "曇後時々晴、雷を伴う" -> result += ",235"
            "曇一時大雨、雷を伴う" -> result += ",236"
            "曇一時雨後晴、雷を伴う" -> result += ",237"
            "曇後一時あられ" -> result += ",238"
            "薄曇後一時雨" -> result += ",239"
            "曇一時晴後時々雨、雷を伴う" -> result += ",240"
            "曇時々大雨" -> result += ",241"
            "曇一時雨後一時晴" -> result += ",242"
            "曇時々雨後晴、雷を伴う" -> result += ",243"
            "曇時々晴、みぞれを伴う" -> result += ",244"
            "曇後時々雨一時晴" -> result += ",245"
            "曇一時大雨" -> result += ",246"
            "雪" -> result += ",247"
            "大雪" -> result += ",248"
            "雪後晴" -> result += ",249"
            "みぞれ後晴" -> result += ",250"
            "雪時々雨後曇" -> result += ",251"
            "雪一時晴" -> result += ",252"
            "雪一時曇" -> result += ",253"
            "雪時々晴" -> result += ",254"
            "雪後一時晴" -> result += ",255"
            "雪時々曇" -> result += ",256"
            "雪後時々曇" -> result += ",257"
            "雪後みぞれ" -> result += ",258"
            "曇後大雪" -> result += ",259"
            "雪後時々雨" -> result += ",260"
            "雪後一時曇、みぞれを伴う" -> result += ",261"
            "みぞれ時々曇後雪" -> result += ",262"
            "雪後曇時々晴" -> result += ",263"
            "大雪後晴" -> result += ",264"
            "みぞれ一時雪後晴" -> result += ",265"
            "雪後一時雨" -> result += ",267"
            "雪後薄曇一時晴" -> result += ",268"
            "雪時々曇後晴" -> result += ",269"
            "雪後みぞれ一時曇" -> result += ",270"
            "雪後晴時々曇、みぞれを伴う" -> result += ",271"
            "雪時々曇一時晴" -> result += ",272"
            else -> result += ",0"
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        realm.close()
    }
}